sudo: true
services: docker

env:
  matrix:
    - OS=ubuntu DIST=16 PACK=deb

branches:
  only:
    - master
    - dev

language: php

php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor

addons:
  apt:
    packages:
      - socat

before_script:
  - composer install

script:
  - make test