sudo: true
services: docker
os: ubuntu
dist: 16

branches:
  only:
    - master
    - dev

language: php

php:
  #- 5.6
  - 7.0
  #- 7.1

cache:
  directories:
    - vendor

addons:
  apt:
    packages:
      - socat

before_script:
  - composer install

script:
  - make test